# docker-compose para criação de ambiente de estudo postgresql
# e pgdmin.

# aqui eu defino um conteiner para o pgdmin4 e outro para o postgresql
# defino as versões mais recentes para cada um.

# atenção nos redirecionamentos de portas e volumes de persistência.
# atualizado para versão mais recente PgAdmin 8.4

version: '3.8'

services:

  pgadmin:
    image: dpage/pgadmin4:8.4
    container_name: pgadmin4
    restart: on-failure
    env_file: var_amb.env
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    ports:
      - 80:80
    depends_on:
      - db

  db:
    image: postgres:16.2
    container_name: postgresql-16.2
    restart: on-failure
    build:
      context: .
      dockerfile: dockerfile
    env_file: var_amb.env
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/pgadmin

volumes:
  postgres_data:
  pgadmin_data:
